[project]
name = "intelligence-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "httpx>=0.28.1",
    "numpy>=2.4.2",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.46",
]
